# Generated by Django 4.2.6 on 2023-10-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0004_alter_bookrate_book_alter_bookrate_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrate',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'один'), (2, 'два'), (3, 'три'), (4, 'четыре'), (5, 'пять')]),
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
    ]
